import UserDetails from "./UserDetails";
import React, { useState } from 'react';
const ManageUserDataJsonWithProps = () => {
    const clientData =
        [{
            "id": 1,
            "first_name": "Maurise",
            "last_name": "Conn",
            "email": "mconn0@jigsy.com",
            "gender": "Male",
            "ip_address": "40.189.91.89",
            "city": "Angadanan"
        }, {
            "id": 2,
            "first_name": "Helenelizabeth",
            "last_name": "Kenworthy",
            "email": "hkenworthy1@amazonaws.com",
            "gender": "Female",
            "ip_address": "161.228.209.166",
            "city": "Sagay"
        }, {
            "id": 3,
            "first_name": "Kennedy",
            "last_name": "Longlands",
            "email": "klonglands2@wsj.com",
            "gender": "Male",
            "ip_address": "51.80.154.246",
            "city": "Somita"
        }, {
            "id": 4,
            "first_name": "Emlyn",
            "last_name": "Andrioletti",
            "email": "eandrioletti3@cargocollective.com",
            "gender": "Genderqueer",
            "ip_address": "111.159.78.242",
            "city": "Dadamtu"
        }, {
            "id": 5,
            "first_name": "Robb",
            "last_name": "Yankin",
            "email": "ryankin4@ocn.ne.jp",
            "gender": "Male",
            "ip_address": "57.201.95.62",
            "city": "Orguz"
        }, {
            "id": 6,
            "first_name": "Devonne",
            "last_name": "Jurczak",
            "email": "djurczak5@etsy.com",
            "gender": "Genderfluid",
            "ip_address": "142.133.229.106",
            "city": "Olszówka"
        }, {
            "id": 7,
            "first_name": "Rogerio",
            "last_name": "Vinall",
            "email": "rvinall6@globo.com",
            "gender": "Male",
            "ip_address": "78.183.67.46",
            "city": "Boa Vista"
        }, {
            "id": 8,
            "first_name": "Muffin",
            "last_name": "Marchetti",
            "email": "mmarchetti7@gravatar.com",
            "gender": "Female",
            "ip_address": "160.128.115.126",
            "city": "Chenyang"
        }, {
            "id": 9,
            "first_name": "Thibaut",
            "last_name": "Matteucci",
            "email": "tmatteucci8@fotki.com",
            "gender": "Bigender",
            "ip_address": "148.237.204.47",
            "city": "Tawala"
        }, {
            "id": 10,
            "first_name": "Boy",
            "last_name": "Cartmail",
            "email": "bcartmail9@exblog.jp",
            "gender": "Male",
            "ip_address": "90.221.58.144",
            "city": "Proletar"
        }, {
            "id": 11,
            "first_name": "Phaedra",
            "last_name": "Tother",
            "email": "ptothera@pagesperso-orange.fr",
            "gender": "Female",
            "ip_address": "1.105.247.120",
            "city": "Longkou"
        }, {
            "id": 12,
            "first_name": "Lona",
            "last_name": "Priest",
            "email": "lpriestb@boston.com",
            "gender": "Bigender",
            "ip_address": "124.10.173.27",
            "city": "Stockholm"
        }, {
            "id": 13,
            "first_name": "Ellery",
            "last_name": "Wickes",
            "email": "ewickesc@alexa.com",
            "gender": "Agender",
            "ip_address": "137.42.117.207",
            "city": "Kalepasan"
        }, {
            "id": 14,
            "first_name": "Marlie",
            "last_name": "Hupka",
            "email": "mhupkad@cam.ac.uk",
            "gender": "Female",
            "ip_address": "15.129.151.242",
            "city": "Mendoza"
        }, {
            "id": 15,
            "first_name": "Sig",
            "last_name": "Segebrecht",
            "email": "ssegebrechte@adobe.com",
            "gender": "Agender",
            "ip_address": "58.21.159.194",
            "city": "Opechenskiy Posad"
        }, {
            "id": 16,
            "first_name": "Jenn",
            "last_name": "Tangye",
            "email": "jtangyef@multiply.com",
            "gender": "Female",
            "ip_address": "249.38.13.175",
            "city": "Nowa Sarzyna"
        }, {
            "id": 17,
            "first_name": "Lanny",
            "last_name": "Sandercock",
            "email": "lsandercockg@multiply.com",
            "gender": "Male",
            "ip_address": "68.160.233.246",
            "city": "Barice"
        }, {
            "id": 18,
            "first_name": "Raoul",
            "last_name": "Witty",
            "email": "rwittyh@theguardian.com",
            "gender": "Male",
            "ip_address": "211.165.57.92",
            "city": "Beausejour"
        }, {
            "id": 19,
            "first_name": "Mata",
            "last_name": "Brockbank",
            "email": "mbrockbanki@istockphoto.com",
            "gender": "Male",
            "ip_address": "27.143.90.73",
            "city": "Alegre"
        }, {
            "id": 20,
            "first_name": "Auberta",
            "last_name": "Bhar",
            "email": "abharj@networkadvertising.org",
            "gender": "Female",
            "ip_address": "250.152.234.198",
            "city": "Ladozhskaya"
        }, {
            "id": 21,
            "first_name": "Berthe",
            "last_name": "Smeeth",
            "email": "bsmeethk@imdb.com",
            "gender": "Female",
            "ip_address": "211.33.191.117",
            "city": "Tyczyn"
        }, {
            "id": 22,
            "first_name": "Ryley",
            "last_name": "Cockrem",
            "email": "rcockreml@networksolutions.com",
            "gender": "Male",
            "ip_address": "82.225.49.244",
            "city": "Zuya"
        }, {
            "id": 23,
            "first_name": "Rosco",
            "last_name": "Dunks",
            "email": "rdunksm@tripadvisor.com",
            "gender": "Male",
            "ip_address": "213.200.108.7",
            "city": "Ergong"
        }, {
            "id": 24,
            "first_name": "Bernardine",
            "last_name": "Kertess",
            "email": "bkertessn@dailymotion.com",
            "gender": "Female",
            "ip_address": "189.227.217.81",
            "city": "Xinpu"
        }, {
            "id": 25,
            "first_name": "Roarke",
            "last_name": "Milson",
            "email": "rmilsono@chronoengine.com",
            "gender": "Male",
            "ip_address": "153.167.240.56",
            "city": "Bang Len"
        }, {
            "id": 26,
            "first_name": "Herold",
            "last_name": "Champkin",
            "email": "hchampkinp@sphinn.com",
            "gender": "Male",
            "ip_address": "228.29.205.110",
            "city": "Mohammedia"
        }, {
            "id": 27,
            "first_name": "Bird",
            "last_name": "Ireland",
            "email": "birelandq@archive.org",
            "gender": "Polygender",
            "ip_address": "152.241.9.100",
            "city": "Gangjia"
        }, {
            "id": 28,
            "first_name": "Dulcine",
            "last_name": "McCreadie",
            "email": "dmccreadier@exblog.jp",
            "gender": "Female",
            "ip_address": "188.166.149.198",
            "city": "Borås"
        }, {
            "id": 29,
            "first_name": "Dew",
            "last_name": "Coultar",
            "email": "dcoultars@prnewswire.com",
            "gender": "Male",
            "ip_address": "196.28.109.43",
            "city": "Daxing"
        }, {
            "id": 30,
            "first_name": "Kristofor",
            "last_name": "Candwell",
            "email": "kcandwellt@meetup.com",
            "gender": "Male",
            "ip_address": "132.66.236.81",
            "city": "Gongnong"
        }, {
            "id": 31,
            "first_name": "Lyell",
            "last_name": "Thurstan",
            "email": "lthurstanu@reference.com",
            "gender": "Male",
            "ip_address": "170.126.73.69",
            "city": "Canggou"
        }, {
            "id": 32,
            "first_name": "Rikki",
            "last_name": "Filov",
            "email": "rfilovv@livejournal.com",
            "gender": "Male",
            "ip_address": "222.163.217.48",
            "city": "Santisimo Rosario"
        }, {
            "id": 33,
            "first_name": "Alejandra",
            "last_name": "Cornuau",
            "email": "acornuauw@newsvine.com",
            "gender": "Female",
            "ip_address": "179.195.69.72",
            "city": "Opatówek"
        }, {
            "id": 34,
            "first_name": "Saidee",
            "last_name": "Kield",
            "email": "skieldx@printfriendly.com",
            "gender": "Female",
            "ip_address": "221.69.212.141",
            "city": "Carcar"
        }, {
            "id": 35,
            "first_name": "Chrysler",
            "last_name": "Pomphrett",
            "email": "cpomphretty@uiuc.edu",
            "gender": "Female",
            "ip_address": "118.40.78.183",
            "city": "Morelos"
        }, {
            "id": 36,
            "first_name": "Jobie",
            "last_name": "Bestwall",
            "email": "jbestwallz@webeden.co.uk",
            "gender": "Female",
            "ip_address": "31.190.183.232",
            "city": "Shanglian"
        }, {
            "id": 37,
            "first_name": "Ree",
            "last_name": "McEniry",
            "email": "rmceniry10@creativecommons.org",
            "gender": "Female",
            "ip_address": "8.54.91.35",
            "city": "Stockholm"
        }, {
            "id": 38,
            "first_name": "Waylen",
            "last_name": "Casbolt",
            "email": "wcasbolt11@sourceforge.net",
            "gender": "Male",
            "ip_address": "249.92.173.94",
            "city": "Lanat"
        }, {
            "id": 39,
            "first_name": "Ewart",
            "last_name": "Threlfall",
            "email": "ethrelfall12@about.me",
            "gender": "Male",
            "ip_address": "133.170.125.249",
            "city": "Umm Ruwaba"
        }, {
            "id": 40,
            "first_name": "Franklyn",
            "last_name": "Williamson",
            "email": "fwilliamson13@shinystat.com",
            "gender": "Agender",
            "ip_address": "31.43.55.63",
            "city": "Bålsta"
        }, {
            "id": 41,
            "first_name": "Brig",
            "last_name": "Haythornthwaite",
            "email": "bhaythornthwaite14@scientificamerican.com",
            "gender": "Male",
            "ip_address": "30.38.52.148",
            "city": "Changhao"
        }, {
            "id": 42,
            "first_name": "Yvor",
            "last_name": "Jentin",
            "email": "yjentin15@lulu.com",
            "gender": "Male",
            "ip_address": "97.13.99.178",
            "city": "Nakajah"
        }, {
            "id": 43,
            "first_name": "Aura",
            "last_name": "Julian",
            "email": "ajulian16@icq.com",
            "gender": "Non-binary",
            "ip_address": "192.127.95.94",
            "city": "Lyaskovets"
        }, {
            "id": 44,
            "first_name": "Loise",
            "last_name": "Buffey",
            "email": "lbuffey17@discuz.net",
            "gender": "Female",
            "ip_address": "199.247.209.8",
            "city": "Zaqatala"
        }, {
            "id": 45,
            "first_name": "Domenic",
            "last_name": "Brimicombe",
            "email": "dbrimicombe18@wired.com",
            "gender": "Male",
            "ip_address": "35.116.63.223",
            "city": "Chengshan"
        }, {
            "id": 46,
            "first_name": "Magdaia",
            "last_name": "Siely",
            "email": "msiely19@unblog.fr",
            "gender": "Female",
            "ip_address": "78.130.118.189",
            "city": "Vista Hermosa"
        }, {
            "id": 47,
            "first_name": "Andria",
            "last_name": "Lukesch",
            "email": "alukesch1a@over-blog.com",
            "gender": "Female",
            "ip_address": "160.126.50.55",
            "city": "Štitar"
        }, {
            "id": 48,
            "first_name": "Dunc",
            "last_name": "de Lloyd",
            "email": "ddelloyd1b@ifeng.com",
            "gender": "Male",
            "ip_address": "248.61.106.29",
            "city": "Naebugis"
        }, {
            "id": 49,
            "first_name": "Arley",
            "last_name": "Balint",
            "email": "abalint1c@dagondesign.com",
            "gender": "Male",
            "ip_address": "77.195.26.1",
            "city": "Qishn"
        }, {
            "id": 50,
            "first_name": "Sidonia",
            "last_name": "Morsey",
            "email": "smorsey1d@themeforest.net",
            "gender": "Female",
            "ip_address": "236.111.68.26",
            "city": "Dauriya"
        }, {
            "id": 51,
            "first_name": "Jonas",
            "last_name": "MacMearty",
            "email": "jmacmearty1e@bluehost.com",
            "gender": "Male",
            "ip_address": "115.136.132.238",
            "city": "Xinjie"
        }, {
            "id": 52,
            "first_name": "Babette",
            "last_name": "Sara",
            "email": "bsara1f@hao123.com",
            "gender": "Female",
            "ip_address": "24.253.231.95",
            "city": "Xarardheere"
        }, {
            "id": 53,
            "first_name": "Barbey",
            "last_name": "Porteous",
            "email": "bporteous1g@exblog.jp",
            "gender": "Female",
            "ip_address": "93.81.222.76",
            "city": "Japeri"
        }, {
            "id": 54,
            "first_name": "Devy",
            "last_name": "Lauga",
            "email": "dlauga1h@geocities.jp",
            "gender": "Male",
            "ip_address": "128.183.119.24",
            "city": "Langpas"
        }, {
            "id": 55,
            "first_name": "Lin",
            "last_name": "Glasscock",
            "email": "lglasscock1i@go.com",
            "gender": "Female",
            "ip_address": "205.82.51.219",
            "city": "Liudaogou"
        }, {
            "id": 56,
            "first_name": "Menard",
            "last_name": "Steven",
            "email": "msteven1j@nba.com",
            "gender": "Male",
            "ip_address": "69.227.116.127",
            "city": "Stockholm"
        }, {
            "id": 57,
            "first_name": "Bryant",
            "last_name": "Khrishtafovich",
            "email": "bkhrishtafovich1k@paypal.com",
            "gender": "Male",
            "ip_address": "219.195.76.227",
            "city": "Zhaocun"
        }, {
            "id": 58,
            "first_name": "Sayer",
            "last_name": "McGriffin",
            "email": "smcgriffin1l@shutterfly.com",
            "gender": "Male",
            "ip_address": "118.180.218.129",
            "city": "Polo"
        }, {
            "id": 59,
            "first_name": "Benoit",
            "last_name": "Stiggers",
            "email": "bstiggers1m@smh.com.au",
            "gender": "Male",
            "ip_address": "102.241.171.162",
            "city": "Montélimar"
        }, {
            "id": 60,
            "first_name": "Madalyn",
            "last_name": "Akhurst",
            "email": "makhurst1n@google.ru",
            "gender": "Female",
            "ip_address": "223.107.242.32",
            "city": "Putinci"
        }, {
            "id": 61,
            "first_name": "Haily",
            "last_name": "Mossop",
            "email": "hmossop1o@gnu.org",
            "gender": "Male",
            "ip_address": "107.252.114.59",
            "city": "Ash Shafā"
        }, {
            "id": 62,
            "first_name": "Willard",
            "last_name": "Cornuau",
            "email": "wcornuau1p@loc.gov",
            "gender": "Male",
            "ip_address": "167.21.106.162",
            "city": "Lezhu"
        }, {
            "id": 63,
            "first_name": "Marco",
            "last_name": "Shropshire",
            "email": "mshropshire1q@businessinsider.com",
            "gender": "Male",
            "ip_address": "78.176.218.192",
            "city": "Zevenaar"
        }, {
            "id": 64,
            "first_name": "Talya",
            "last_name": "Winsborrow",
            "email": "twinsborrow1r@angelfire.com",
            "gender": "Female",
            "ip_address": "8.233.72.241",
            "city": "Pucyura"
        }, {
            "id": 65,
            "first_name": "Andrey",
            "last_name": "Cammidge",
            "email": "acammidge1s@booking.com",
            "gender": "Male",
            "ip_address": "41.47.228.124",
            "city": "Cuiabá"
        }, {
            "id": 66,
            "first_name": "Blaine",
            "last_name": "Keneforde",
            "email": "bkeneforde1t@amazon.co.uk",
            "gender": "Polygender",
            "ip_address": "146.89.193.100",
            "city": "Ol’ginskaya"
        }, {
            "id": 67,
            "first_name": "Lucila",
            "last_name": "Dorgon",
            "email": "ldorgon1u@yellowpages.com",
            "gender": "Agender",
            "ip_address": "93.132.234.123",
            "city": "Tsibulev"
        }, {
            "id": 68,
            "first_name": "Melanie",
            "last_name": "Mapham",
            "email": "mmapham1v@altervista.org",
            "gender": "Female",
            "ip_address": "226.103.196.176",
            "city": "Tanumshede"
        }, {
            "id": 69,
            "first_name": "Haslett",
            "last_name": "Crocombe",
            "email": "hcrocombe1w@nydailynews.com",
            "gender": "Male",
            "ip_address": "31.106.148.40",
            "city": "Konstantynów"
        }, {
            "id": 70,
            "first_name": "Andria",
            "last_name": "Loftin",
            "email": "aloftin1x@virginia.edu",
            "gender": "Female",
            "ip_address": "162.108.183.95",
            "city": "Yuanlin"
        }, {
            "id": 71,
            "first_name": "Brandon",
            "last_name": "Cowpland",
            "email": "bcowpland1y@aol.com",
            "gender": "Male",
            "ip_address": "209.247.230.185",
            "city": "Pakis"
        }, {
            "id": 72,
            "first_name": "Charlean",
            "last_name": "Bristo",
            "email": "cbristo1z@vistaprint.com",
            "gender": "Female",
            "ip_address": "96.8.238.195",
            "city": "Dongjiao"
        }, {
            "id": 73,
            "first_name": "Dex",
            "last_name": "Lung",
            "email": "dlung20@yolasite.com",
            "gender": "Male",
            "ip_address": "50.102.174.35",
            "city": "Pineleng"
        }, {
            "id": 74,
            "first_name": "Haleigh",
            "last_name": "Wheelwright",
            "email": "hwheelwright21@symantec.com",
            "gender": "Male",
            "ip_address": "197.67.14.13",
            "city": "Maraã"
        }, {
            "id": 75,
            "first_name": "Marleen",
            "last_name": "Hexam",
            "email": "mhexam22@earthlink.net",
            "gender": "Female",
            "ip_address": "2.100.142.177",
            "city": "Labuhanlalar"
        }, {
            "id": 76,
            "first_name": "Dorolisa",
            "last_name": "Karpe",
            "email": "dkarpe23@tinyurl.com",
            "gender": "Female",
            "ip_address": "7.0.247.112",
            "city": "Fujiayan"
        }, {
            "id": 77,
            "first_name": "Michele",
            "last_name": "Couve",
            "email": "mcouve24@reddit.com",
            "gender": "Male",
            "ip_address": "157.55.48.118",
            "city": "Caibarién"
        }, {
            "id": 78,
            "first_name": "Raven",
            "last_name": "Romney",
            "email": "rromney25@springer.com",
            "gender": "Female",
            "ip_address": "129.18.227.250",
            "city": "Guadalupe"
        }, {
            "id": 79,
            "first_name": "Cecelia",
            "last_name": "Shooter",
            "email": "cshooter26@un.org",
            "gender": "Polygender",
            "ip_address": "162.86.19.211",
            "city": "Tekstil’shchiki"
        }, {
            "id": 80,
            "first_name": "Louella",
            "last_name": "Mabbot",
            "email": "lmabbot27@netlog.com",
            "gender": "Female",
            "ip_address": "62.46.22.217",
            "city": "San Mateo"
        }, {
            "id": 81,
            "first_name": "Felicio",
            "last_name": "Klainman",
            "email": "fklainman28@nytimes.com",
            "gender": "Male",
            "ip_address": "67.52.4.107",
            "city": "Novorossiysk"
        }, {
            "id": 82,
            "first_name": "Kris",
            "last_name": "Chiswell",
            "email": "kchiswell29@irs.gov",
            "gender": "Male",
            "ip_address": "208.167.31.89",
            "city": "Fort Worth"
        }, {
            "id": 83,
            "first_name": "Roxanna",
            "last_name": "Fleckness",
            "email": "rfleckness2a@addthis.com",
            "gender": "Female",
            "ip_address": "162.160.200.241",
            "city": "Zhoupi"
        }, {
            "id": 84,
            "first_name": "Kinsley",
            "last_name": "Aylwin",
            "email": "kaylwin2b@angelfire.com",
            "gender": "Male",
            "ip_address": "245.240.105.40",
            "city": "Mounlapamôk"
        }, {
            "id": 85,
            "first_name": "Hartwell",
            "last_name": "Whitlam",
            "email": "hwhitlam2c@arstechnica.com",
            "gender": "Male",
            "ip_address": "165.207.133.13",
            "city": "Braunschweig"
        }, {
            "id": 86,
            "first_name": "Joyce",
            "last_name": "Dark",
            "email": "jdark2d@dedecms.com",
            "gender": "Female",
            "ip_address": "203.157.136.193",
            "city": "Xinji"
        }, {
            "id": 87,
            "first_name": "Valentijn",
            "last_name": "Herley",
            "email": "vherley2e@clickbank.net",
            "gender": "Male",
            "ip_address": "91.98.158.179",
            "city": "Selorejo"
        }, {
            "id": 88,
            "first_name": "Anton",
            "last_name": "Stretton",
            "email": "astretton2f@friendfeed.com",
            "gender": "Male",
            "ip_address": "117.37.141.181",
            "city": "Bajo Pichanaqui"
        }, {
            "id": 89,
            "first_name": "Bondie",
            "last_name": "Flower",
            "email": "bflower2g@free.fr",
            "gender": "Male",
            "ip_address": "120.2.207.125",
            "city": "Petaling Jaya"
        }, {
            "id": 90,
            "first_name": "Creighton",
            "last_name": "Rolph",
            "email": "crolph2h@telegraph.co.uk",
            "gender": "Male",
            "ip_address": "122.134.41.116",
            "city": "Danao"
        }, {
            "id": 91,
            "first_name": "Jarrad",
            "last_name": "Glasner",
            "email": "jglasner2i@wikipedia.org",
            "gender": "Male",
            "ip_address": "240.191.207.50",
            "city": "Diofior"
        }, {
            "id": 92,
            "first_name": "Van",
            "last_name": "Jenne",
            "email": "vjenne2j@baidu.com",
            "gender": "Agender",
            "ip_address": "8.67.26.36",
            "city": "Charlton"
        }, {
            "id": 93,
            "first_name": "Enos",
            "last_name": "Anning",
            "email": "eanning2k@mail.ru",
            "gender": "Male",
            "ip_address": "189.120.146.250",
            "city": "Roshchino"
        }, {
            "id": 94,
            "first_name": "Avictor",
            "last_name": "Spacey",
            "email": "aspacey2l@blogger.com",
            "gender": "Agender",
            "ip_address": "227.227.31.217",
            "city": "Kiten"
        }, {
            "id": 95,
            "first_name": "Rebekah",
            "last_name": "Gerrelts",
            "email": "rgerrelts2m@geocities.jp",
            "gender": "Female",
            "ip_address": "187.136.59.81",
            "city": "Usman’"
        }, {
            "id": 96,
            "first_name": "Steffane",
            "last_name": "Jessop",
            "email": "sjessop2n@blogspot.com",
            "gender": "Female",
            "ip_address": "230.101.148.228",
            "city": "Boketu"
        }, {
            "id": 97,
            "first_name": "Mendie",
            "last_name": "Mosson",
            "email": "mmosson2o@boston.com",
            "gender": "Male",
            "ip_address": "78.97.143.6",
            "city": "Motupe"
        }, {
            "id": 98,
            "first_name": "Robinson",
            "last_name": "Bassano",
            "email": "rbassano2p@ocn.ne.jp",
            "gender": "Male",
            "ip_address": "176.211.253.163",
            "city": "Bhamdoûn el Mhatta"
        }, {
            "id": 99,
            "first_name": "Irvin",
            "last_name": "Caldero",
            "email": "icaldero2q@auda.org.au",
            "gender": "Male",
            "ip_address": "154.109.169.8",
            "city": "Kuala Lumpur"
        }, {
            "id": 100,
            "first_name": "Friedrick",
            "last_name": "Alekhov",
            "email": "falekhov2r@bloglovin.com",
            "gender": "Male",
            "ip_address": "101.60.18.68",
            "city": "San Agustín Acasaguastlán"
        }];

    const [list] = useState(clientData);

    return(
        <div>
            <ul>
                {list.map(search => <li key = {clientData.id}><UserDetails 
                    name = {search.name}
                    email = {search.email}
                    sex = {search.sex}
                    city = {search.city}
                    /></li>)}
            </ul>
        </div>
    )
}

export default ManageUserDataJsonWithProps;